import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quadiro Technologies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          variables: {
            colorText: '#ffffff',
            colorPrimary: '#1e90ff',
            colorBackground: '#1c1c1c',
            colorInputBackground: '#2a2a2a', 
            colorInputText: '#ffffff',
            colorTextOnPrimaryBackground: '#ffffff'
          },
          elements: {
            socialButtonsBlockButton: 'bg-[#2a2a2a]',
            socialButtonsBlockButtonText: 'text-[#ffffff]',
            socialButtonsBlockButtonText__google: 'text-[#ffffff]',
            button: 'text-[#ffffff] hover:text-[#e0e0e0]',
            badge: 'text-[#ffffff]'
          }
        }}
      >
        <body className={`${inter.className} dark`}>
          <NextSSRPlugin
            routerConfig={extractRouterConfig(ourFileRouter)}
          />
          <main className="w-full h-full bg-[#0a0a0a]">
            {children}
          </main>
        </body>
      </ClerkProvider>
    </html>
  );
}